# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprpaper & waybar & hypridle
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] $terminal
# exec-once = $terminal
# exec-once = nm-applet &
