general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 8, y = 4}

[font]
size = 14.0
# normal = { family = "JetBrainsMono Nerd Font" }
# bold = { family = "JetBrainsMono Nerd Font"}
# italic = { family = "JetBrainsMono Nerd Font"}
# bold_italic = { family = "JetBrainsMono Nerd Font"}

normal = { family = "DepartureMono Nerd Font" }
bold = { family = "DepartureMono Nerd Font"}
italic = { family = "DepartureMono Nerd Font"}
bold_italic = { family = "DepartureMono Nerd Font"}
