# Colorscheme
source=./modules/colorscheme.conf

# Monitor settings
source=./modules/monitors.conf

# General settings (appearance)
source=./modules/general.conf

# Programs
source=./modules/programs.conf

# Keybinds
source=./modules/keybinds.conf

# Environment variables
source=./modules/env.conf

# Input settings
source=./modules/input.conf

# Rule settings
source=./modules/rules.conf
