return {
	-- 	"WhoIsSethDaniel/mason-tool-installer.nvim",
	-- 	dependencies = {
	-- 		{ "mason-org/mason.nvim", opts = {} },
	-- 		"mason-org/mason-lspconfig.nvim",
	-- 	},
	--
	-- 	opts = {
	-- ensure_installed = {
	-- 				-- Linters
	-- 				"codespell",
	-- 				"eslint_d",
	-- 				"htmlhint",
	-- 				"markuplint",
	-- 				"pylint",
	-- 				"selene",
	-- 				"stylelint",
	-- 				"vale",
	-- 				-- Formatters
	-- 				"black",
	-- 				"isort",
	-- 				"pint",
	-- 				"prettier",
	-- 				"prettierd",
	-- 				"stylua",
	-- 			},
	-- 	}
}
