set -sa terminal-overrides ",xterm*:Tc"
set -s escape-time 0

# Enable mouse control
set -g mouse on

# Set start index of windows to start at 1
set -g base-index 1

# Reload config file (change file location to your the tmux.conf you want to use)
unbind r
bind r source-file ~/.tmux.conf

# Remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Split panes using o and v
unbind %
unbind '"'
unbind o
unbind v

bind o split-window -h
bind v split-window -v
bind -r ^ last-window

# Switch panes using prefix + direction keys
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# Status bar
set -g status on
set -g status-position top
set -g status-justify left
set -g status-style "bg=#060606,fg=#e4e4e8"
set -g status-interval 5

# Left status
set -g status-left-length 40
set -g status-left "#[bg=#1c1c1c,fg=#e4e4e8] #S "

# Right status
set -g status-right-length 60
set -g status-right "#[fg=#9eb38e] #h"
set -ag status-right "#[fg=#e4e4e8] %H:%M"
set -ag status-right "#[fg=#75a1c7] %Y-%m-%d"

# Tabs
set -g window-status-format "#[bg=#060606,fg=#888888] (#I) #W "
set -g window-status-current-format "#[bg=#1c1c1c,fg=#e4e4e8] [#I] #W "
set -g window-status-separator ""
set -g window-status-activity-style "bg=#060606,fg=#c2916a"
set -g window-status-bell-style "bg=#40000a,fg=#e4e4e8,bold"

# Panes
set -g pane-border-style "fg=#1c1c1c"
set -g pane-active-border-style "fg=#75a1c7"
set -g display-panes-colour "#888888"
set -g display-panes-active-colour "#75a1c7"

# Messages/command line
set -g message-style "bg=#1c1c1c,fg=#e4e4e8"
set -g message-command-style "bg=#1c1c1c,fg=#c4a8d6"

# Copy mode/selection
set -g mode-style "bg=#404040,fg=#e4e4e8"

# Clock
set -g clock-mode-colour "#75a1c7"
set -g clock-mode-style 24

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
